mrcnn_path: ./dependencies/Mask_RCNN
deeplab_path: ./dependencies/deeplab-pytorch
panopticapi_path: ./dependencies/panopticapi

mrcnn_weights: weights/mask_rcnn_coco.h5

coco_dir: ./dataset/coco

coco_ann_path: ./dataset/coco/val2017/annotations/instances_val2017.json

data_set: val2017

image_limit: 5

panoptic_gt_json_path: ./dataset/coco/val2017/annotations/panoptic_val2017.json

results_folder: ModelResults

instance_result_json: instance_segmentation_results
semantic_result_json: semantic_segmentation_results

panoptic_results_folder: PanopticResults
